[quote.epigraph, , Juan 4:29]
____
Venid, ved a un hombre que me ha dicho todo cuanto he hecho.
¿No será éste el Cristo?
____

[short="La Vida y Los Escritos de William Bayly"]
== Una Selección de la Vida y Escritos de William Bayly

En la luz y vida eterna de Dios,
con la que yo y toda la humanidad ha sido alumbrada en una medida,
permanezco ahora en victoria y gozo sobre el mundo y sobre toda su gloria y enemistad,
sobre la bestia y el falso profeta tanto interna como externamente,
al haber recibido poder del Padre de vida por andar en el camino de Sus juicios,
en pos de quien mi alma por mucho tiempo había suspirado y estado sedienta,
incluso desde la niñez; aunque en ese entonces no sabía qué era lo que mi alma anhelaba,
pero ahora sé que los misterios del reino eterno
de Dios son revelados a los niños que le temen,
pero para los demás están escondidos en parábolas.

Cuando tenía cerca de diez años,
recuerdo que a veces deseaba ir a sentarme solo en silencio en
algún lugar solitario donde pudiera lamentarme y llorar en secreto,
incluso hasta que mi corazón se quebrantara,
aunque yo no sabía por qué. Comencé a orar a Dios en temor y con lágrimas,
y aunque no sabía quién era o dónde estaba, y tenía muy poco que decir, aun así,
algo clamaba en mí, y suspiraba por Dios,
creyendo confiadamente que Dios me escuchaba desde donde sea que estuviese,
y que se apiadaría de mí y me salvaría,
y por esto se levantaban en mí agradecimientos a Él. En ese entonces
no sabía que había una semilla en mí que era y es amada por Dios,
que es contraria a la corriente de este mundo,
a la cual le pertenecen las bendiciones y las promesas,
y la cual se levantaba a veces en mí, en la quietud de mi mente,
para destruir todo lo que la serpiente y mi propia voluntad
habían formado en mi corazón que era contrario a Dios,
para que así pudiera gozar de paz en el pacto eterno de luz.
Porque cuando en cualquier momento que yo hacía o
decía algo que era contrario a la voluntad de Dios,
rápidamente era reprendido por ello, juzgado y condenado,
y atemorizado por Su testigo en mi conciencia, el cual veía todos mis caminos y palabras,
por muy secretos que fueran.
Esta es la misma luz de la que habló Job,
que "`me hacía responsable de las iniquidades de mi juventud, vigilaba todas mis sendas,
y ponía límites a las plantas de mis pies.`"^
footnote:[Job 13:26-27]
Y en esta luz puedo ver todo cuanto he hecho, y recuerdo el primer juramento que hice,
cuando fui provocado por otro muchacho,
y como fui golpeado con temblor y casi no podía estar
de pie por causa del testigo de Dios en mi conciencia,
aunque entonces no sabía qué era, y hubiera querido huir lejos de él,
al haber sido llevado a un temor tan horrible y sintiéndome
condenado por él cada vez que hacía algún mal.
Por lo tanto, como dice la Escritura,
no existe un lugar donde los que hacen maldad se
puedan esconder de la temible presencia de Dios.^
footnote:[Job 34:22, Salmos 139:7-12]

Así, cuando tenía como quince años, fui a los soldados (cuando era tiempo de guerra),
no prestando atención al verdadero guía--la luz y
Espíritu de Dios--que a menudo contendía conmigo,
a fin de guiarme en mansedumbre y temor, y alejarme de toda guerra y pleito,
las cuales vienen de las pasiones^
footnote:[Santiago 4:1-2]
que combaten contra el alma.
Yo entonces me uní a ellos y me volví uno entre ellos,
tanto en la guarnición como en el ejército,
donde por un tiempo fui guardado y preservado de
mucha iniquidad por el temor de Dios en mí,
aunque en ese momento no sabía dónde estaba Él,
ni lo supe por mucho tiempo después. Sin embargo, mediante Su mano secreta de poder,
inesperada e inmerecidamente,
era preservado cuando muchos eran asesinados a mi derecha y a mi izquierda.
Gloria y alabanzas sean dadas a Su poder por los siglos de los siglos.

Pero cuando tenía cerca de diecisiete años,
estaba bajo el comando de un mayor general llamado Edward Massey,
donde conocí a muchos hombres impíos y malvados,
y algunos de ellos eran los que se habían apartado del ejército del coronel Goring.
A causa de esta compañía,
la semilla de honestidad en mi fue traicionada e incluso matada,
y yo comencé a endurecerme contra el temor de Dios; porque apenas era un joven,
que tenía un semblante tímido por naturaleza,
y a menudo era reprendido en mi conciencia por algún mal,
y sentía condenación por ello rápidamente.
Pero ahora, en medio de esta compañía,
podía jurar y jactarme y a veces beber hasta embriagarme,
y crecí en la iniquidad al punto de que incluso me deleitaba en jurar y en embriagarme.
Sin embargo, a veces, cuando estaba lejos de mis compañeros, y estaba solo y quieto,
se apoderaba de mí un miedo y un pavor que venían del testigo de Dios en mi conciencia,
causándome un terror muy grande y horrible.
Y en la noche a menudo era aterrorizado y atormentado en
sueños con visiones espantosas del infierno y de demonios,
de muerte y condenación, que, en verdad,
en ese estado hubiera sido mi justa porción. Y así en el momento fresco del día,^
footnote:[Génesis 3:8 LBLA]
oía la voz de Dios y tenía miedo, como Adán en la transgresión;
y aunque con gusto hubiera querido ocultar mi pecado, como lo intentó Adán, aun así,
el Señor lo descubría. Y ahora sé que "`Dios le habla al hombre en una o en dos maneras;
pero el hombre no entiende, por sueños, en visión nocturna,
cuando el sueño cae sobre los hombres, cuando se adormecen sobre el lecho,
para quitar al hombre de su obra y apartar de él la soberbia.`"^
footnote:[Job 33:14-17]

Continué en esta compañía durante casi dos años, hasta que toda la compañía fue disuelta.
Alrededor de este tiempo fui tan golpeado por el
testigo de Dios (la luz de Cristo en mi conciencia),
que empecé a dejar los juramentos y el desenfreno.
Hasta mis profanos amigos se me hicieron abominables y pesados,
y desde entonces hasta este día nunca más hice un juramento,
que fue hace como diez años. Así que, con el tiempo,
comencé a sentirme un poco entusiasmado al oír a los sacerdotes,
y comencé a escudriñar las Escrituras y a hablar mucho de ellas,
como hacen ahora muchos profanos con el fin de hacerse una cubierta.
En ese entonces pensaba que debía ser guiado por los sacerdotes,
quienes habían aprendido y tenían conocimiento de los lenguajes,
que ellos llamaban "`el original,`" sin saber en
ese entonces que su original había comenzado en Babel,
donde Dios confundió los lenguajes, y que, al principio, antes de esto,
las personas eran de una sola lengua.
Así que su original viene de Babel, que es confusión, y ellos todavía permanecen allí,
junto con todos sus seguidores,
los cuales también recibirán parte de sus plagas si no salen a la luz de Cristo,
que es el verdadero original.
Porque Su luz era antes de Babel, y antes de los sacerdotes, o del latín,
griego y hebreo que Pilato puso sobre Cristo, el verdadero Profeta,
que todos deben escuchar; cuyo nombre es la Palabra de Dios,
la cual era en el principio.^
footnote:[Juan 1:1]
Pero el pobre, ignorante y ciego, que ha salido de la luz que alumbra a todo hombre,
insiste junto con los sacerdotes que el griego y el hebreo son el original,
y que las Escrituras no pueden entenderse sin ellos,
sin considerar que los que sabían el latín,
el griego y el hebreo crucificaron al Hijo de Dios,
quien en el principio estaba glorificado con el Padre, antes que el mundo fuese,
y quien es el verdadero original, por quien el mundo fue hecho.
Y para los griegos Su cruz era locura, y para los judíos tropezadero.
Y los griegos sabían griego, y los judíos sabían hebreo,
como también los sacerdotes y Pilato,
pero no conocieron al Hijo de Dios--el original--sino que pusieron su latín,
griego y hebreo sobre Él cuando lo crucificaron.^
footnote:[Juan 19:19-20]

Así que por un tiempo
comercié con estos mercaderes de Babilonia,
recibiendo y comprando sus mercaderías,
teniendo la esperanza de que estas cosas que había
recibido de ellos fueran riquezas buenas y permanentes,
al ver que la gente las estimaba tanto;
porque las personas exclamaban que solo los sacerdotes tenían el original,
y podían dar el significado de las escrituras, y nadie más;
y así la bestia sostenía o llevaba a la gran ramera, y todos se maravillaban de ellas,
como yo también lo hice en aquel entonces.
Pero finalmente algo en mí empezó a despertarse cada vez más,
y a sentir hambre del verdadero pan; sin embargo,
pensaba que todavía debía ser alimentado en la mesa de ellos, y así continué,
hasta casi morir de hambre con las algarrobas que comían los cerdos.
Porque había una palabra despertándose en mi corazón que yo sentía diciendo,
"`dame comida,
o de lo contrario pereceré;`" y yo hasta con lágrimas iba
a escucharlos muchas veces debido al hambre que sentía,
hasta que percibí que ellos no hablaban la Palabra de vida a partir de la boca del Señor,
el verdadero Pan que desciende del cielo,
sino que habían estudiado y armado algo a partir de las Escrituras,
mezclando sus propios significados y sabiduría babilónica con la sutileza de la serpiente,
e invitándonos a sentarnos y a escuchar la palabra de Dios.
Y así nosotros buscábamos luz, pero he aquí que éramos alimentados con tinieblas y polvo;
y esa semilla en mí, a la cual el Señor Dios le proclamaba gozo y libertad,
era contristada por ellos,
como lo era por los engañadores y falsos profetas en las eras pasadas.

Y esto puedo decir con verdad, y testificar en el Señor:
que cuando la verdadera hambre y sed del Dios vivo se levantaron en mí,
a menudo era herido, entenebrecido y despojado por la sabiduría terrenal,
la filosofía carnal y las mentiras vanas que salían de la boca de los sacerdotes.
Este conocimiento carnal me desviaba de mi galardón,
arrastrando mi mente fuera de la medida pura del don de Dios en mi interior,
al punto que la semilla de simpleza,
honestidad y mansedumbre que se había despertado
en mí se cansó y no quiso oírlos más. Y en este momento,
no había ninguna otra razón por la que yo negara a estos maestros,
excepto que sentía el don de Dios en mí descubriéndolos y testificando contra ellos,
como aquellos que "`ningún provecho hicieron al pueblo,`"^
footnote:[Jeremías 23:32]
porque estaban fuera de Su consejo y no eran capaces
de apartar a nadie de sus malos caminos,
sino que más bien fortalecían las manos del impío, y entristecían al justo.
Esta es su obra, como es evidente por sus frutos,
cuya recompensa será conforme a sus hechos.

Así mi alma fue despertada en aquellos días por el testigo de Dios en el corazón,
por medio del cual sentía el pecado como una carga,
y a menudo me daba miedo pensar en la muerte y miseria eterna,
pero no sabía cómo salir de debajo del poder del pecado y de la muerte,
ni escapar de la ira por venir, ya que no conocía a Aquel que salva de estas cosas,
el cual es Cristo, el poder de Dios,
que "`alumbra a todo hombre que viene a este mundo,`"^
footnote:[Juan 1:9 Reina Valera de Gómez]
y "`condena el pecado en la carne.`"^
footnote:[Romanos 8:3]
Pero ahora veo que el pueblo perece por falta de conocimiento,
y que "`los que guían al pueblo lo extravían; y los guiados por ellos se pierden.`"^
footnote:[Isaías 9:16 LBLA]
Porque nada puede ayudar o satisfacer el alma anhelante e inmortal,
salvo el eterno y verdadero pan de vida, el poder de Dios,
que Él les da a todos los que lo reciben,
cuyo poder condena por el pecado y destruye las obras del diablo,
quien tiene el poder de la muerte; porque "`el aguijón de la muerte es el pecado.`"^
footnote:[1 Corintios 15:56]
De este modo Cristo libra a los hombres de lo que causa su esclavitud,
y del temor de la muerte.
Sí, libra a todos los que creen en Aquel que es la resurrección y la vida,
sobre quien la segunda muerte no tiene potestad.
¡Gloria al Señor por los siglos de los siglos!

Así, habiendo empezado en una medida a dejar a los sacerdotes, me mantuve en casa,
no queriendo por un tiempo ir a escuchar a nadie,
sino más bien permanecer solo y estar en silencio.
Esto fue una gran cruz para mis padres, esposa y relaciones, y también para algo en mí,
y para mis compañeros y conocidos,
que me amaban con ese amor que rápidamente se convirtió en odio.
Así que encontré difícil romper con las costumbres en las que vivía,
y vivir de manera contraria a todos mis vecinos y conocidos,
y perder el amor de todos ellos,
como veía que sucedería si seguía esa luz que me dejaba ver a los sacerdotes,
y la vanidad del mundo.
Hallé que las Escrituras no dicen en vano: "`¿Mudará el etíope su piel,
y el leopardo sus manchas?
Así también, ¿podréis vosotros hacer bien, estando habituados a hacer mal?`"^
footnote:[Jeremías 13:23]
Escuchen esto ustedes descuidados, que viven en la vanidad de sus mentes,
contendiendo por sus costumbres, vanidades,
tradiciones y modas de un mundo que yace en maldad,
y por los deseos carnales que batallan contra sus almas.
Todo esto se volverá su plaga en el día de su visitación,
y eso en lo que ustedes se han deleitado más, se volverá su más grande tormento.
Entonces sabrán que fueron advertidos en su vida.

Pero en medio de mis pruebas y tentaciones internas y externas,
había una Palabra muy cerca de mí, en mi propio corazón,
aunque en ese entonces yo no sabía qué era lo que me decía:
"`Busca primeramente el reino de Dios,
y pon tu mente en la vida eterna;`" y no sabía dónde buscarlo ni encontrarlo.
Pero la profunda consideración de esto me fortalecía para seguir a Dios,
y algunas veces incluso suspiros y clamores ascendían
desde el prisionero de esperanza en mí,
y mi corazón a veces era quebrantado y derretido por el poder de la Palabra de vida,
la cual sentía allí martillando mi dureza y rasgando
el velo que me separaba de la paz con Dios.
Pero aun así, todavía no conocía a "`Cristo en mí, la esperanza de gloria,`"^
footnote:[Colosenses 1:27]
quien "`alumbra a todo hombre que viene a este mundo,`"^
footnote:[Juan 1:9 Reina Valera de Gómez]
"`cuyo nombre es: la Palabra de Dios,`"^
footnote:[Apocalipsis 19:13]
"`el varón que abre la matriz, santo al Señor,`"^
footnote:[Lucas 2:23]
"`el Cordero que fue inmolado desde el principio del mundo`"^
footnote:[Apocalipsis 13:8]
(que yace en iniquidad), "`el Primero y el Último,`"^
footnote:[Isaías 48:12; Apocalipsis 1:17, 2:8, 22:13]
"`El Santo en medio de nosotros;`"^
footnote:[Isaías 12:6; Oseas 11:9]
al cual mi alma amaba, pero quien había sido traspasado, herido, y, por así decirlo,
matado en mí, como la semilla que sufrió en Sodoma y Egipto,
aunque Él es Señor de señores, y Rey de reyes.

Así comencé a prestar atención y a amar esa luz en mí que descubría el pecado y la vanidad,
y ponía en evidencia la corriente del mundo entero, y yo la tomé como mi compañera,
(o "`parienta,`"^
footnote:[Proverbios 7:4]
como habla Salomón de la sabiduría),
no sabiendo que era la luz de Cristo (la sabiduría y poder de Dios) en mi conciencia,
en aquellos días de ignorancia.
Pero por ella a menudo vi mi propia locura,
y que el mundo entero estaba fuera de su correcto curso (o camino de paz),
en confusión y abominación, sin temor de Dios delante de sus ojos, en orgullo,
en envidia uno de otro, en codicia y desenfreno, en hipocresía y falsedad,
cada uno buscando sus propios intereses y ganancias, desde el juez hasta el sacerdote,
y así también sus seguidores,
sin que se encontrara entre ellos un hombre sabio
que temiera a Dios y se apartara del mal.
Esto vi, y algunas veces hasta me entristecía cuando lo consideraba,
deseando en mi corazón tener poder para ayudar, sintiendo mucho deseo de unidad y paz,
de mansedumbre y quietud, de amor y justicia entre los hombres,
para que pudieran vivir como hijos de un solo padre; y decía en mi mente:
"`¿No vinimos todos de Adán? ¿Y no teníamos todos
un solo padre y una sola madre al principio?
¿Qué razón tiene, pues,
el hombre para envidiarse unos a otros, y ser altivos,
orgullosos y duros uno contra otro, y matarse uno a otro por un pequeño pedazo de tierra,
o para buscar la vanagloria que se marchitará? ¿Qué razón tiene el hombre para odiar,
contender, estar enojado por la religión, y por sus juicios y opiniones,
e incluso pelearse entre sí por estas cosas?`"

Cuando consideraba estas cosas en mi mente,
deseaba en mi corazón que Dios remediara todo esto, y que finalmente terminara con ello;
porque yo incluso sentía a toda la creación gimiendo
en esclavitud bajo estas opresiones en ese tiempo.
Sin embargo,
todavía no sabía que era la luz de Cristo en mí (que
a veces me reprendía por el pecado y la maldad),
la que me mostraba estas cosas,
y abría mi entendimiento para que pudiera conocer
y entender esas cosas que conducen a mi paz eterna.
De modo que ahora puedo decir con seguridad,
"`el pueblo es destruido por falta de conocimiento;`"^
footnote:[Oseas 4:6 Reina Valera 1602 Purificada]
y que "`estrecha es la puerta, y angosto el camino que lleva a la vida,
y pocos son los que la hallan,`"^
footnote:[Mateos 7:14]
y que los misterios del reino están "`escondidos de los sabios y entendidos del mundo,
pero revelados a los niños,`"^
footnote:[Mateos 11:25; Lucas 10:21]
y a aquellos que se hacen ignorantes por amor a Cristo, quien es la luz del mundo,
la sabiduría y el poder de Dios.
Gloria en las alturas a Aquel que me sacó de las tinieblas a Su luz admirable,
en la que contemplo Su semejanza.

Ahora bien, en estos días,
cuando hasta me había determinado nunca más oír a los sacerdotes,
ni ser un seguidor de ellos, aun así, estando sin mi empleo externo,
y por el temor de perderlo todo,
por las persuasiones de la serpiente en mí y de otros fuera de mí,
fui a escucharlos otra vez,
no fuera que hiciera molestar a los que tenían intención de contratarme y preferirme.
Pero por esto fui juzgado y condenado terriblemente por el testigo de Dios en mi corazón,
el cual antes me había dejado ver el engaño de los sacerdotes,
y la vanidad y error de su adoración y de sus métodos,
que eran contrarios a Cristo y a Sus apóstoles y sus doctrinas.

Así que en el proceso del tiempo hice dos viajes cortos a Francia, en los que,
teniendo tiempo libre, la serpiente llevó mi mente totalmente a lo externo,
a deleitarme en el arte de la aritmética, y en el estudio y práctica de la navegación,
que veía que podía alcanzar en poco tiempo, estando muy familiarizado con los números,
que es el fundamento de muchas artes.
Estas búsquedas me llevaron a un monte muy alto,
y me mostraron promesas gloriosas de preferencia, riqueza,
del amor del mundo y de respeto entre los hombres,
cosas que agradaban a la naturaleza en mí que se
había apartado del testigo de Dios--a saber,
la vanagloria de la vida, que no es del Padre, sino del mundo.
Esta en verdad es la gloria de los hombres ricos,
de los hombres grandes y de los capitanes principales,
cuya carne será entregada a las aves que vuelan en
medio del cielo en la gran cena de Dios.

Así, a través de las fuertes tentaciones y seducciones de esta halagadora ramera,
(ese espíritu que se aparta de la luz,
de cuya copa han bebido todas las naciones y reyes de la tierra),
la honesta y tierna semilla de equidad, amor y mansedumbre fue cubierta,
extraviada y estaba como muerta en mí. Y dejé entrar al espíritu del mundo
como un torrente (cuyo fundamento había sido conmovido antes en una medida,
y la tierra que yacía sobre la preciosa semilla había
sido removida parcialmente por el poder de Dios),
y profundas tinieblas cubrieron mi alma nuevamente, y escondieron su vida y paz de ella,
que anteriormente había sentido y anhelado.
Así que puedo certificar la siguiente escritura:
"`Porque los que quieren enriquecerse caen en tentación y lazo,
y en muchas codicias necias y dañosas,
que hunden a los hombres en destrucción y perdición.`"^
footnote:[1 Timoteo 6:9]
Sin embargo,
en el tiempo que estuve en Francia fui guardado suficientemente en el
temor de Dios por Su testigo puro (la luz de Cristo en mi conciencia,
que me mostraba el pecado y la maldad),
como para no atreverme a ser lascivo o a embriagarme,
aunque no sabía que era la luz de Cristo la que estaba obedeciendo en ese momento,
la cual me salvó de todo eso a lo que el diablo me habría arrastrado.
Así que ahora puedo decir junto con Jacob que "`El Señor estaba en este lugar,
y yo no lo sabía.`"^
footnote:[Génesis 28:16]
Por lo tanto, todos los pueblos, vengan a Aquel que les dice todo cuanto han hecho;^
footnote:[Juan 4:29]
porque si conocieran el don de Dios, y amaran al Señor,
ustedes le pedirían a Él el agua viva; pero "`los rebeldes habitarán en tierra seca.`"^
footnote:[Salmos 68:9]

Pero, aunque fui preservado de muchos males externos, aun así,
el amor de este mundo y de las cosas del mundo tenía una fortaleza en mi corazón,
por la cual el verdadero amor a la equidad,
a la justicia y a la misericordia se había desvanecido,
y yo no sabía dónde hallar el lugar de la sabiduría,
aunque la buscaba diligentemente cuando sentía la pérdida de ella.
Pero en la cruz para la voluntad del hombre y de la carne,
es donde nace eso que hereda el reino de la paz de Dios.
Porque después de un tiempo,
cuando estaba en medio de mis vanos pensamientos e imaginaciones,
considerando cómo construir grandes cosas en la tierra, cómo hacerme rico,
conocido y honorable en ella,
y cómo obtener la amistad del mundo y la alabanza de los hombres,
de repente vino sobre mí un freno, que como una nube cubrió todo.
Fui golpeado con un silencio muy tranquilo en mi mente (como
Adán cuando escuchó la voz del Señor al fresco del día),
en el cual vi que había estado luchando y agotándome a mí mismo por pura vanidad,
por cosas que perecen con el uso, y que yo, como un necio,
podría irme y dejarlas todas a la mitad de mis días. Así,
cuando le presté atención a eso que me dejaba ver
cómo estas cosas no eran más que una sombra,
y cómo era una locura buscar tan fervientemente eso
que podría tomar alas y volar lejos de mí,
y privarme así de la corona eterna de descanso para mi alma inmortal,
entonces fue que mi antigua condición vino a mi memoria nuevamente,
y comencé a sentir algo despertándose en mí por vida,
lo cual por mucho tiempo había yacido en muerte y
esclavitud bajo Faraón en el Egipto espiritual,
y fue como si un clamor se levantara del prisionero, gimiendo desde lejos por libertad.
Y entonces comencé a ser angustiado y condenado en mí mismo,
y mi paz en la tierra fue quebrantada,
y la espada encendida giraba en todas direcciones sobre ella.
Entonces, teniendo miedo de la vergüenza,
comencé a contender contra el Espíritu de Dios en mí,
(sin saber qué era durante todo este tiempo, ni por algún tiempo después),
y me deshacía de mi aflicción tanto como podía. Pero
algunas veces deseaba ser manso como otros,
porque a menudo me encontraba experimentando la verdad de las palabras de Salomón:
"`Aun en la risa tendrá dolor el corazón,`"^
footnote:[Proverbios 14:13]
y me di cuenta de que muchas veces estaba más cerca de llorar que de alegrarme
en ese tipo de compañía. Así que mi alma no tenía descanso en aquellos días,
cuando no conocía a mi Maestro, el verdadero Pastor de Israel,
el cual les da vida eterna a Sus ovejas (que lo siguen),
cuya vida es mansa y humilde de corazón.

Pero en ese tiempo mi alma, siendo como una que es despertada del sueño,
y estando hambrienta de eso que satisface,
comenzó nuevamente a buscar la verdadera comida y descanso,
y disfrutar esa vida y paz que no cambian.
Entonces pensé en mi mente,
"`¿Que haré?`" --recordando que los sacerdotes (quienes habían sido descubiertos
por el mismo testigo de Dios en mi corazón) eran consoladores miserables,
médicos nulos, que "`recubrían con lodo suelto`"^
footnote:[Ezequiel 13:10-16]
y mataban la semilla inocente y justa en los corazones de la gente ignorante.

Entonces, sin saber qué hacer para encontrar vida (habiendo salido a cazar comida afuera,
como Esaú y toda su descendencia), fui a los Bautistas,
a ver si podía obtener descanso y paz ahí entre ellos, pensando que,
si ellos eran el pueblo de Dios, yo tenía derecho de tener comunión con ellos,
y de participar de sus promesas y privilegios.
Porque a menudo sentía algo en mí que era amado por Dios,
y por lo tanto concluía que era uno de los elegidos,
sin conocer ni discernir en ese entonces la diferencia entre las cosas,
y cómo las promesas y las bendiciones le pertenecen a una semilla
_en_ el hombre (que puede ser oprimida y hollada por él),
y que la elección fue hecha antes de la fundación del mundo,
pero que el mundo entero yace en maldad.
Lean esto si pueden, ustedes que dicen que la elección es de un pueblo particular,
y que el resto es dejado a su propia cuenta;
y tengan cuidado de las doctrinas de demonios.
Y recuerden que "`Dios no hace acepción de personas,`"^
footnote:[Hechos 10:34]
y que Cristo, la verdadera luz, "`alumbra a todo hombre que viene al mundo.`"^
footnote:[Juan 1:9 Reina Valera de Gómez]
Es en Él que se experimenta la elección y la redención;
y los reprobados son los que no conocen a Cristo en su interior,
como dicen las Escrituras.^
footnote:[2 Corintios 13:10]

Así que entonces me volví un seguidor constante de los Bautistas,
y finalmente entré en esa comunión y hermandad con
ellos cuyo fundamento era el agua natural,
carnal y visible;
porque antes de haber sido hundido en agua, ellos no me llamaban hermano,
pero repentinamente después, ellos lo hacían. Sin embargo,
después de haber sido hundido era el mismo que antes en todos los sentidos,
y de ninguna manera me sentía mejorado o más satisfecho por el agua que antes.
Y cuando venía nuevamente al testigo de Dios en mí, en el momento fresco del día,
él me dejaba ver cómo mi alma todavía yacía en muerte,
aunque mi mente entendedora había encontrado un tipo
de vida y comida en una profesión religiosa,
en la que no tenía verdadera paz luego de haber realizado
y hecho todo por lo que había esperado alcanzarla.
De hecho, la paz seguía huyendo de mí,
cada vez que me volvía al don de Dios en mi corazón,
el cual me dejaba ver mi estado y condición, a saber, la luz de Cristo,
aunque en ese entonces no sabía lo que era.
Pero ahora sé que "`no hay paz para los impíos,`"^
footnote:[Isaías 48:22; 57:21]
y que el ay es para los que se "`cobijan con cubierta y no del Espíritu puro de Dios,`"^
footnote:[Isaías 30:1]
que convence al mundo de pecado; y que nunca habría alcanzado la paz así,
aunque hubiera andado en estos caminos por cien años. Porque nosotros
no veníamos verdaderamente a Cristo (sino más bien lo negábamos),
cuya carne es el verdadero pan que da vida al mundo.
Ni tampoco estábamos unidos en la unidad de la fe del Hijo de Dios,
la cual es un "`misterio que se guarda en una conciencia pura,`"^
footnote:[1 Timoteo 3:9 Traducción Literal del Inglés]
"`que da victoria sobre el mundo,`"^
footnote:[1 Juan 5:4]
y brota de esa luz con la que Cristo nos ha alumbrado a todos,
para dar el conocimiento de Dios a las personas,
en el cual se experimenta la verdadera herencia y comunión de los santos.

Pero nosotros estábamos edificando una torre en nuestras propias imaginaciones,
esperando que la cúspide llegara al cielo,
como los confundidos edificadores de la antigüedad,
como descendientes de Nimrod que cazaba delante del Señor,
el principio de cuyo reino fue Babel,
que es ese espíritu que confunde a todos los que edifican sin la luz de Cristo,
que es la piedra de ángulo y el cimiento estable.
Porque, aunque ustedes digan "`Señor,
Señor,`" aun así esto no les será de ningún provecho
mientras todavía sean hacedores de iniquidad.
Y así nosotros estábamos profesando y hablando de la verdad que hace libre--que es Cristo,
la luz, el camino al Padre--pero permanecíamos en esclavitud, oscuridad y falsedad,
en el camino espacioso en el que muchos hipócritas, obreros fraudulentos, envidiosos,
orgullosos y codiciosos pueden caminar.
Porque estos pueden mantener puesta su cubierta de profesión religiosa,
y hablar de Aquel que saca de la muerte y lleva a la vida,
pero aun así "`detener la verdad en injusticia,`"^
footnote:[Romanos 1:18]
manteniendo abajo Su testigo (la luz que alumbra todo hombre),
que les deja ver cuando ustedes no tienen el verdadero pan de vida, que da paz,
descanso y satisfacción al alma, sino que se alimentan de algarrobas.
Y a pesar del gran ruido que hacen con respecto a Aquel que es la sustancia de todo,
quien pone fin a las sombras, aun así,
ustedes esperan Su reino y gloria y gobierno externamente.
¡Oh insensatos y ciegos! ¿No está el reino de Dios dentro de ustedes?^
footnote:[Lucas 17:21 Reina Valera 1602 Purificada]
¿Y no es "`la hija del rey toda gloriosa en su __interior__`"?^
footnote:[Salmos 45:13 Reina Valera de Gómez]
¿Y no dijo el Rey, "`No salgáis;`" y cuando ellos dijeran, "`Mirad, aquí está el Cristo,
o mirad, allí está, no lo creáis?`"^
footnote:[Mateo 24:23]

Pero en este estado estuve con ustedes,
hasta que el Hijo de Dios abrió los ojos de aquel que había nacido ciego,
a quién los fariseos habían expulsado (como han expulsado a muchos en esta era,
que tiemblan ante la Palabra del Señor).
Y en ese entonces vi en Su luz eterna,
que una profesión religiosa sin vida nunca traería
paz a esa parte que se había despertado en mí,
que suspiraba en pos del poder puro y justo del Dios vivo.
Porque es de esta vida y poder que todos los hombres se
han desviado y se han vuelto ajenos por causa de la transgresión,
que es "`la pared intermedia de separación`"^
footnote:[Efesios 2:14]
que debe ser derribada a medida que se trabaja la salvación con temor y temblor.
Pero los profesantes de religión niegan esto,
expulsando a los que tiemblan ante la Palabra viva y poderosa,
que discierne los pensamientos y las intenciones del corazón;
de modo que ha venido verdaderamente el tiempo "`cuando no sufrirán la sana doctrina.`"^
footnote:[2 Timoteo 4:3]
Esto es para todos ustedes, sacerdotes, bautistas y pueblo,
que han salido de esa luz que alumbra a todo hombre,
que les deja ver sus obras impías y sus malas palabras.
¿Qué más les diré? Bueno, que ustedes evaden el juicio,
y por lo tanto no conocen el amor de Dios.
Esto viene del Señor Dios para ustedes, como confesarán en su lecho de muerte.

Así que después de pasar un tiempo en esta condición desesperada y anhelante que tenía,
en la que deseaba que Dios hiciera un cambio o algo diferente entre nosotros (sintiendo
que en todo lo que realizábamos estábamos muertos a la vida pura y simple de Dios,
de la que mi alma estaba sedienta),
aconteció que oí a alguien leyendo un libro respecto a los
sufrimientos de algunos del pueblo de Dios llamado Cuáqueros,
en un calabozo en Suesham.
Este nombre y estos sufrimientos eran desconocidos para mí en ese tiempo; sin embargo,
al oír de ellos,
algo en mí se levantó con mucha ternura y compasión hacia este pueblo inocente y sufrido,
que sacó lágrimas de mis ojos, creyendo que sufrían por causa de la conciencia.
Y esa misma "`cosa`" dentro de mí incluso decía en ese momento,
que Dios un día vengaría la sangre de ellos en sus sangrientos perseguidores--lo
cual ahora ha sido ejecutado por Su mano fuerte de poder sobre algunos de ellos,
incluso hasta el punto de cortarlos de la tierra como espinos y cardos para el fuego.
Pero aún durante todo este tiempo yo no sabía qué era lo que me dejaba ver estas cosas,
y no podía distinguir la luz de las tinieblas,
como es el estado de miles que ahora profesan a Cristo en palabras, como yo lo hacía,
pero no lo conocen como un Líder de Sus ovejas que guía
fuera de las tinieblas al rebaño de vida y paz eterna.

Entonces escuché de los libros de Jacob Behmen, y comencé a leerlos mucho,
y a reunir algo de ellos en mi propia comprensión y en las imaginaciones de mi cerebro;
pero esto y todo lo demás no le daban paz y descanso a mi alma inmortal,
que todavía yacía en muerte y esclavitud a causa de la transgresión y del pecado.

Pero no mucho tiempo después de esto,
un ministro de la palabra de vida (cuyo nombre pocos conocen),
vino y le predicó a mi espíritu en prisión,
el cual se regocijó mucho en el sonido de sus palabras,
a las cuales les presté atención diligentemente,
y fui convencido eternamente de que fue la verdad misma lo que él declaró,
y que no había otro camino para conocer a Dios, o para ser salvos,
sino caminando en esa luz con la que Él ha alumbrado a todo hombre,
la cual me dejaba ver todas las malas palabras y obras impías que había cometido.
Esta luz viene de Cristo, el Salvador,
y lleva a todos los que la siguen fuera del mal que está en el mundo,
hacia Aquel que era antes que el mundo fuese (glorificado
al lado del Padre) y por quien el mundo fue hecho.
Él es la sustancia de todos los tipos, figuras, sombras y ordenanzas,
de los cuales se podrían decir muchas cosas, pero Cristo es la suma,
quien redime al hombre por Su Sangre (a saber,
Su vida) de la tierra (a la cual el hombre fue arrastrado
por la transgresión) y lo lleva a Dios nuevamente,
el cual era antes de la transgresión y quien es el principio y el fin.

Y así, a medida que mi corazón y mi mente estaban vueltos a la verdadera luz,
muchas escrituras venían nuevamente a mí, confirmando la verdad de lo que él dijo.
Y el poder de la Palabra en mi corazón,
que es de Dios (de quien viene la luz) comenzó a despertarse y a obrar,
y la condenación fue ministrada sobre todas mis antiguas profesiones religiosas.
Entonces vino una espada sobre mi tierra, la cual todavía estaba en paz;
y una guerra abierta contra la bestia, la ramera, y el falso profeta,
fue proclamada por el Cordero inmolado, cuya espada salía de Su boca.
Y el prisionero de esperanza se regocijó al comienzo de este día de venganza,
creyendo que el año de la redención había llegado.
En verdad, un gran cambio había comenzado, que me pareció extraño,
y fue rápidamente percibido por los Bautistas,
quienes entonces eran mis compañeros en la religión,
pero no en la tribulación. Porque fui llevado a llorar y a lamentarme,
al ver que todas las religiones en el mundo no eran más que una hoja marchita
cuando carecían de la vida y poder puro de Dios que salva de pecado,
y lleva a ser uno con Él; de modo que ya no podía sentirme satisfecho,
ni vivir de palabras acerca de Dios y de Cristo,
cuando no disfrutaba del verdadero descanso, es decir,
de la leche espiritual no adulterada de la Palabra inmortal de vida que mi alma anhelaba,
incluso desde la niñez, aunque yo no sabía qué era, ni dónde encontrarla.

Pero durante esta mi atribulada condición,
muchos Bautistas me siguieron día y noche tratando de persuadirme a salir de ella,
mirándome como si estuviera engañado.
Unos con oraciones,
otros con halagos y otros con palabras envidiosas
se esforzaban por hacerme volver a ellos,
diciéndome que había caído de la gracia, que estaba bajo la ley,
y que por lo tanto estaba haciendo nula la sangre de Cristo.
Pero en ese entonces yo no sabía que la sangre era la vida,
y que la vida era la luz de los hombres;
y a pesar de que estaba convencido en mi conciencia de la verdad eterna,
estaba confundido en mi entendimiento,
y el día del Señor era como de tinieblas y no de luz para esa parte en mí que
había detenido la verdad en injusticia (como todos confesarán algún día,
cuando sean arrancadas sus cubiertas, y sea manifestado el interior de sus corazones).
Así estos, con sus abundantes palabras, sacaron mi mente del testigo de Dios en mí,
y la alejaron de la ley escrita en el corazón,
en la cual debí haberme mantenido y a la cual debí haberle sido fiel--a saber,
esa "`Palabra profética más segura,`"^
footnote:[2 Pedro 1:19]
que me dejaba ver todo cuanto había hecho.
Y así, para obtener reposo, aparté mi mente de la verdad (que es requerida en lo íntimo),
y escuché a espíritus engañadores, y palabras que oscurecen el consejo,
al punto de que volví a unirme a ellos con más celo que antes,
y animé a otros a seguir sus fuertes imaginaciones de la letra de la escritura,
buscando a un Salvador externo, aunque las Escrituras dicen, "`Cristo en vosotros,
la esperanza de Gloria;`"^
footnote:[Colosenses 1:27]
y "`¿No os conocéis a vosotros mismos, que Jesucristo está en vosotros,
a menos que estéis reprobados?`"^
footnote:[2 Corintios 13:5] etc.
De hecho, nosotros esperábamos Su venida fuera de nosotros,
aunque Él dijo que cuando "`alguno dijere: Mirad, aquí está el Cristo, o mirad,
allí está, no lo creáis,`" y "`No salgáis;`"^
footnote:[Mateo 24:23-26]
y buscábamos un reino y gloria externos,
aunque está escrito que la hija del rey es toda gloriosa en su interior,^
footnote:[Salmos 45:13 Reina Valera de Gómez]
y el Rey dijo, "`El reino de Dios dentro de vosotros está.`"^
footnote:[Lucas 17:21 Reina Valera 1602 Purificada]
Y nosotros esperábamos Su resurrección y vida únicamente como un evento externo,
mientras que Él dijo,
"`Yo soy la resurrección y la vida,`" y "`Yo he venido como una luz al mundo,`"
(que alumbra a todo hombre que viene a este mundo.) Estas cosas las imaginábamos,
y nos edificábamos el uno al otro en semejantes ideas,
aunque eran contrarias a las Escrituras,
y a los santos que se edificaban en esa fe que es
un misterio escondido en una conciencia pura.^
footnote:[1 Timoteo 3:9]
Y así pasábamos por alto el juicio (como los fariseos e hipócritas antiguos,
quienes "`decían pero no hacían`"^
footnote:[Mateo 23:3]) tratando de subir por otro camino
más fácil que entrar por la puerta (que es Cristo,
el cual "`condena al pecado en la carne`"^
footnote:[Romanos 8:3]), como un ladrón que intenta hurtar la cubierta de otro hombre.

Pero después de un tiempo, estas cosas me eran una carga muy pesada,
y me di cuenta de que estas mentiras eran más difíciles de juzgar y destruir
que todas las demás maldades e iniquidades que había cometido.
Porque cuando (estando insatisfecho) me alejé de los bautistas otra vez,
me determiné a esperar en el Señor con propósito de corazón,
sin importar lo que sucediera con todo el mundo, su gloria, religión o enemistad.
Porque encontré una palabra despertándose poderosamente en mí, que decía,
"`busca primeramente el reino de Dios,`" y yo le presté atención a ella,
volviendo mi mente otra vez a esa luz que me había reprendido por
el pecado desde mi niñez. Y entonces el poder de Dios se manifestó,
y Sus temibles juicios cayeron sobre la ramera que había
salido de la vida a la estéril profesión religiosa;
y luego las plagas, el hambre, los terremotos, los truenos, la guerra y los temblores,
gemidos, clamores, llantos,
ayunos y el gran espanto vinieron sobre esa parte
en mí que antes había profesado las escrituras.
Y todo lo que había hecho o dicho fuera de la luz, fue juzgado,
maldecido y condenado--ya sea que comiera o no comiera, bebiera o no bebiera,
me echara o me levantara, durmiera o velara,
saliera o entrara--todo fue juzgado y condenado,
hasta que Aquel que es manso vino como rey montado sobre un pollino de un asna,
y Sion fue redimida con juicio.
Esto sucedió en la medida que obedecía el poder del Señor,
quien con Su espada fuerte y penetrante, castigó al leviatán,
y mató al dragón que estaba en el mar,
y la gran ramera fue herida (la bestia y el falso profeta juntos),
de cuya copa de fornicación todas las naciones y los reyes de la tierra han bebido,
y quienes ahora deben beber, como yo lo he hecho,
del cáliz del vino del ardor de la ira del Señor Dios Todopoderoso,
o de lo contrario ellos nunca conocerán el descanso
y la paz en la tierra de los vivientes.

Porque yo vi y sentí como Caín, el primer nacimiento, el envidioso, el homicida,
es un errante apartado de Dios; e Ismael, el salvaje, el escarnecedor, es echado fuera;
y Esaú, el diestro en la caza, es rechazado; y como los profanos,
y todos los que son de la descendencia de Amán, y de la raza de Nabal,
tendrán su porción en el lago de tormento.
Porque cuando la mente del hombre salió de la sumisión a la vida que lo formó,
entró en la propiedad y lugar de las bestias, aves y reptiles,
y entonces la verdadera vida que creó todas las cosas
comenzó a actuar en el hombre como un angustiador,
reprobador y condenador,
mostrando cómo él había salido de su correcto lugar
y morada en el que fue creado y colocado.
Y así el hombre, al sentirse perturbado,
peleó contra la luz de la vida que lo angustiaba
y lo juzgaba secretamente (cuya vida es Dios),
y entonces se llenó de ira, rabia y rebelión,
que incluso estaba listo para levantar su mano contra cualquier cosa que se le opusiera,
no teniendo ningún lugar de descanso en la vida de justicia que lo formó,
y dejando que su corazón se fuera a lo externo, a las propiedades de las bestias.
Aquí se dio a luz a Ismael, el nacimiento de la carne, cuya "`mano es contra todos,`"^
footnote:[Génesis 16:12]
y aquí el hombre en la transgresión tiene miedo de Dios su Creador,
y es echado a la tierra como Adán.

Pero vi que no fue que Dios, el Creador,
quiso o se propuso sacar a los hombres de Su presencia
y echarlos a las propiedades externas,
terrenales y bestiales; sino que el hombre,
al apartarse de Él por hacer lo que es contrario a Su voz y vida pura,
se halla perturbado por ello, y siente la ira o enemistad de su Creador a causa de ello,
el cual está contristado y enojado por la desobediencia de Sus criaturas.
Y, por lo tanto, para aliviarse de esta angustia,
el hombre huye más a los diferentes pensamientos y cosas que le ocasionan aún más ira,
tormento y angustia a su propia alma; como Saúl,
que buscó música para aquietarse con ella cuando se había
apartado del verdadero Espíritu y vida de su Creador.
Pero el hombre en el principio (antes de toda invención)
fue engendrado en Adán en la vida de justicia,
en la cual todo estaba quieto y sujeto a Dios, quien es el reposo,
paz y tranquilidad de todos los que viven en Él.
Pero al salir de esto a las propiedades de las bestias,
el hombre es contaminado y profanado,
y se da cuenta (como dicen las Escrituras) que no hay descanso para el impío.

Así también Caín salió de la verdadera vida,
e hizo un sacrificio de la propiedad externa de las bestias, en el cual no fue aceptado,
y por eso él fue perturbado y juzgado por la vida interna
que lo formó (en cuya vida Abel presentó su ofrenda).
Así Caín se enojó y se llenó de ira contra su hermano, y lo mató,
porque Abel ofreció el sacrificio a Dios desde ese principio
interno o propiedad espiritual en la que fue formado,
(que era su morada adecuada) y por lo tanto fue aceptado,
y en esta vida él era agradable a Dios, su Creador.
Pero Caín habiendo salido de lo interno a lo externo,
ofreció lo que era externo en las propiedades terrenales y bestiales,
que no alcanzaban lo interno, ni podían ser aceptadas por Dios.
Y teniendo un sentido de su rechazo, este lo reprochaba, juzgaba y angustiaba,
de modo que su semblante decayó y estaba enojado contra su hermano.
Esta es la señal de Caín en todas las eras, a saber:
el nacimiento externo en las propiedades carnales y externas,
que persigue el nacimiento interno y espiritual en la propiedad de Dios.
En verdad, esto comenzó en Caín y Abel, como está escrito,
"`el que había nacido según la carne,`" o el nacimiento externo,
"`perseguía al que había nacido según el Espíritu,`" o la vida interna, que es de Dios.
Y así también es ahora, como pueden ver todos los que han nacido de la propiedad de Abel.

Por lo tanto, todos ustedes hijos de Adán, consideren en qué naturaleza han nacido,
y viven, y ofrecen su sacrificio; porque Dios no puede ser burlado;
ustedes segarán lo que han sembrado, y no será de otra manera.
Si están en el nacimiento externo, que es de la carne,
entonces no son aceptados por el purísimo Dios invisible, sino más bien juzgados,
perturbados y condenados por Él, que es la razón por la cual están irritados,
opuestos y molestos contra aquellos que (en el nacimiento
interno y espiritual) son más justos que ustedes.
Porque tanto ustedes como su conocimiento permanecen en las propiedades orgullosas,
rebeldes y tercas de los animales irracionales,
en las cuales hablan mal de cosas muy internas que no entienden;
y en ese estado jamás las entenderán, hasta que lleguen a la vida interna que los formó,
la cual es más profunda,
elevada y excelente que la vida animal o externa en la que
ustedes ofrecen su sacrificio a un Dios no conocido,
que no lo acepta de sus manos.

Porque los que son del nacimiento de la carne se acercan con sus bocas y sus labios,
pero su corazón está lejos.
Se acercan en lo externo, pero lo interno se mantiene alejado,
y ellos siguen separados de eso en lo que se encuentra la aceptación. Por lo tanto,
no se engañen;
porque Caín y Abel solo son entendidos correctamente en lo interno y espiritual,
y nada se esconde de Aquel que crea todas las cosas,
que es a quien tenemos que darle cuenta.
Y aquí también Jacob y Esaú son claramente conocidos y manifestados,
el uno siendo el varón quieto, que habitaba en tiendas, y el otro un diestro en la caza,
hombre del campo, como dan testimonio las Escrituras.
Y Dios dice, "`A Jacob amé,
más a Esaú aborrecí.`" ¿Pero cómo puede ser que Él ame a uno y aborrezca a otro cuando
apenas son niños? Es por la misma razón que Él miró con agrado a Abel y a su ofrenda,
pero no a Caín y a su ofrenda.
La razón se encuentra en los nacimientos o propiedades internas por las que fueron generados,
gobernados y movidos, y no en sus personas o nombres externos.
Porque Dios no hace acepción de personas o nombres externos.
Pero Jacob habla del varón quieto que habitaba en tiendas, es decir, en la vida interna,
que es su morada apropiada,
en la que se experimenta y se manifiesta el amor y la aceptación
para el nacimiento espiritual en todas las edades.

Pero Esaú, que era aborrecido, era un diestro cazador, un hombre del campo.
Noten que era esta naturaleza o propiedad la que era aborrecida, y no la persona,
que en sí misma no es más que tierra.
Y aquí encontramos al hombre del campo,
la mente totalmente cautiva en la naturaleza animal, cazadora y errante, es decir,
en las propiedades externas donde la bendición no se puede obtener.
Porque ciertamente, la bendición es el derecho de Jacob en la tienda,
quien de hecho es antes de que el diestro cazador apareciera; sí,
y en verdad Jacob será bendito.
El que lee, entienda; porque estos dos nacimientos todavía existen en este día.

Y aquí también la vida de Enoc, Abraham, Isaac, Moisés, los profetas,
de Cristo y los apóstoles es conocida, en el movimiento,
semilla o vida interior que los formó;
cuya vida es tan desconocida para los hijos de la carne, o nacimiento externo,
como lo que está en el fondo del océano es desconocido
para el que está sobre la superficie de las aguas.
Porque el hombre natural, como está escrito,
solo conoce lo que puede discernir naturalmente, como animales irracionales,
en cuya propiedad él además se corrompe a sí mismo.
Pero el hombre espiritual, interno o quieto conoce todas las cosas,
al permanecer en la tienda, y en el consejo del Creador de todas las cosas.

Y está escrito que "`Enoc caminó con Dios, y desapareció; porque le llevó Dios.`"^
footnote:[Génesis 5:24]
Pero "`Nimrod, el vigoroso cazador delante del Señor`"^
footnote:[Génesis 10:9]
(el principio de cuyo reino es Babel,
o confusión) todavía se encuentra hoy entre los cazadores vigorosos y diestros,
que siempre salen a cazar la vida interna, preciosa y sustancial,
que para ellos sigue siendo desconocida.
Y esto se hizo evidente en Caín, Ismael, Esaú, Amán, Judas, Herodes,
y muchos más que se podrían nombrar, en muchos sumos sacerdotes,
gobernadores y personas que eran de la carne, y estaban en el reino del orgullo,
sutileza, envidia, ira y persecución, que es de Babel--siempre de caza tras la presa,
es decir,
tras el nacimiento interno que camina con Dios en la vida invisible de aceptación.

Y Cristo vino en esta vida, manifestando Su origen o Padre al mundo;
pero el nacimiento externo o carnal no lo conoció ni lo recibió, a pesar de que el mundo,
y todo lo que en él hay, fue hecho y formado por Él y para Él. En lugar de esto,
ellos persiguieron Su vida preciosa desde el día en que nació hasta su muerte,
como vemos en el rey Herodes,
que no conocía la vida del Hijo de Dios cuando se manifestó,
estando él en las propiedades externas de este mundo para el cual lo interno es un misterio;
como está escrito,
"`Grande es el misterio de Dios... que ninguno de los príncipes de este siglo conoció,
porque si lo hubieran conocido, no habrían crucificado al Señor de gloria.`"^
footnote:[1 Timoteo 3:16, 1 Corintios 2:8]
Porque el conocimiento, entendimiento,
reino y gloria de estos hombres externos están únicamente en las propiedades visibles,
terrenales y animales, en las que yace la enemistad contra la vida invisible,
interna y justa del Cordero inocente--quien no pelea por Su reino,
adoración o sacrificio como Caín y su generación,
sino más bien ora a Su Padre que ellos puedan ver en qué espíritu,
propiedad o nacimiento están,
para que entonces se vuelvan internamente en sus mentes a Su reino,
el cual Cristo les dijo que está dentro de ellos y no afuera,
mandándolos a buscarlo en justicia, y entonces todo lo externo estará en sujeción,
y todas las cosas buenas serán añadidas.

Consideren esto ahora, todos ustedes hijos del nacimiento externo o carnal,
que viven y actúan en la enemistad y en la vida corrupta de las propiedades animales,
separados de la vida interna,
pura y eterna del Hacedor y Creador del cielo y de la tierra.
Vuelvan rápidamente sus mentes a lo interno y estén quietos,
deseando fervientemente poder conocer a Dios,
y regresar a eso que puede trasladar a Su reino, lo cual es algo invisible y no externo,
que yace escondido en ustedes.
Sí, vuelvan sus mentes hacia eso de lo que internamente se han separado.
Porque el fundamento del falso nacimiento y del falso profeta es este:
que el hombre sale de la vida interna de justicia y verdad,
y solo piensa en las cosas externas y visibles,
en las que él (como un diestro cazador) busca satisfacer las inclinaciones,
concupiscencias y deseos de la vida animal.
Pero esta vida de Esaú es juzgada y reprobada en ustedes por la vida interna,
que es la vida de Dios, y el fundamento de Enoc, Abel, Abraham,
y del resto de esa generación. Y si ustedes no son edificados sobre este fundamento,
a través del arrepentimiento de las obras y de la naturaleza de injusticia,
entonces caerán con Caín y Judas, con Esaú y Amán,
y con el resto de esa generación (sin esperanza de ser restaurados)
al abismo infinito de oscuridad y miseria que no tienen fin.
_Porque horrenda y temible cosa es vivir y morir en esa naturaleza,
nacimiento y propiedad, con la que Dios nunca_ se reconcilia, sino al contrario,
la aborrece para siempre como una abominación. Y el aliento,
los tiempos y las sazones de ustedes están en Su mano,
y ustedes no pueden arrepentirse cuando quieran, o en su propio tiempo predeterminado;
sino solo cuando la vida interna de Dios se mueva,
descubriendo y reprendiendo los malos caminos,
palabras y acciones que ustedes manifiestan.
Solo cuando Él llama es posible volverse ante Sus reprensiones.

Porque así dice Dios el Creador, "`No contenderá mi espíritu con el hombre para siempre,
porque ciertamente él es carne,`"^
footnote:[Génesis 6:3]
es decir,
porque ciertamente un nacimiento carnal de este mundo ha entrado al alma del hombre.
Por lo tanto, consideren a Esaú, quien era de este nacimiento carnal,
y no halló lugar de arrepentimiento,
o un camino para regresar (al ser endurecido en su profanidad, Hebreos 12:17^
footnote:[RV 1602 Purificada]).

Porque les digo a partir de un conocimiento certero de la vida misteriosa de la creación,
que si ustedes gastan todo su tiempo sin el verdadero conocimiento del único
Dios sabio e invisible--conocimiento que solo se obtiene al experimentar Sus
juicios sobre todos los velos o nacimientos de la carne,
y sobre todas las propiedades degeneradas de la injusticia--y si no llegan,
por medio de dichos juicios,
a tener unidad con Él en la vida interna y escondida de justicia,
serán arrastrados a la más densa oscuridad y tinieblas
en la cual están los ayes y las miserias para siempre.
Porque no es todo el que puede decir con su boca, "`Señor,
Señor,`" el que entrará en el reino de Dios, sino aquel que ha nacido de nuevo,
que ha sido traspuesto como Enoc,
y que es de ese nacimiento del Espíritu que estaba en Abel,
por el cual él ofreció a su Hacedor un sacrificio
más excelente que Caín. Únicamente este nacimiento,
y ningún otro, es aceptado por Dios, y camina con Él desde el tiempo de Abel hasta hoy.

Por lo tanto, no piensen que el reino o misterio de piedad consiste en cosas externas,
o en señales visibles; porque yo les digo, no;
es algo más profundo que la faz de la tierra,
la cual hasta los hipócritas pueden discernir.
Caven ahora, ustedes que pueden, y encuentren esta perla de gran precio,
que es capaz de trasladar o recrear el alma.
Porque ha amanecido el día en el cual todas las cosas visibles e invisibles serán
claramente conocidas y manifestadas para ese nacimiento que Dios acepta.
Ni tampoco el reino de justicia consiste en satisfacer la carne,
los deseos de los ojos u oídos, o la vanagloria de la vida;
porque estas cosas no provienen del Padre, sino del mundo o del nacimiento de la carne,
y del reino de los poderes animales de la oscuridad,
en el cual el Dios justo y santo y Su reino no es visto, conocido,
entendido ni disfrutado en ninguna medida.

Por lo tanto, estén quietos,
y aprendan a conocer el evangelio eterno que ahora
es "`predicado en toda criatura bajo el cielo,`"^
footnote:[Colosenses 1:23 traducción literal del griego]
diciendo, "`Temed a Dios, y dadle gloria, porque la hora de Su juicio ha llegado.`"^
footnote:[Apocalipsis 14:7]
Porque por este evangelio, Caín (el errante) y su sacrificio son puestos en evidencia,
y las cosas escondidas de Esaú (el diestro cazador,
que pierde la bendición) son sacadas a la luz.
Y por este evangelio Jacob obtiene la herencia, y el sacrificio de Abel es aceptado,
pero el primer nacimiento de la carne es rechazado para siempre.

Por lo tanto,
todos los pueblos sobre la faz de la tierra consideren lo que ahora les digo.
Una medida de la verdadera luz de la vida les ha
sido dada por el Señor Dios de infinita misericordia,
para que ustedes no perezcan,
sino que por medio de ella sean guiados fuera del nacimiento carnal y del mundo,
a la vida y paz eterna.
Sí,
"`a cada uno de ustedes le ha sido dada la manifestación del Espíritu de Dios para provecho.`"^
footnote:[1 Corintios 12:7]
Por lo tanto, puesto que ustedes deben dar cuenta en el día de Dios, grande y terrible,
tengan cuidado de no apartarse de Su gracia para vivir en desenfreno,
vanidad e iniquidad;
porque en está condición ustedes siempre se quejarán
de que carecen de gracia y de poder para cambiar,
y de este modo acusarán a Dios neciamente.
Porque los murmuradores o querellosos no son sino los que andan en sus propios deseos
impíos. Pero "`la gracia de Dios que trae salvación se ha manifestado a todos los hombres,
y ella nos enseña a renunciar a la impiedad y a las concupiscencias mundanas,
y a vivir en este presente mundo, sobria, justa y piadosamente.`"^
footnote:[Tito 2:11-12 Reina Valera de Gómez]
Esta es la luz que viene del unigénito Hijo de Dios, que dijo,
"`Yo soy la luz del mundo;`" y todos los que lo siguen saben que "`todas
las cosas que son reprobadas son hechas manifiestas por la luz,
porque lo que manifiesta todo, es la luz.`"^
footnote:[Efesios 5:13 Reina Valera de Gómez]

Sí, la verdadera luz del Hijo de Dios, Jesucristo,
que "`alumbra a todo hombre que viene al mundo,`" es eso que les
manifiesta o les muestra secretamente sus malas obras,
su conducta impía, su ligereza y vanidad de mente,
y también es lo que les deja ver los sentimientos
de orgullo y envidia escondidos en sus corazones,
y los reprende y reprueba muchas veces en secreto por sus malas palabras,
y por las cosas duras que han hablado, y por sus pensamientos vanos y malvados,
por lo cual se enciende un fuego en ustedes secretamente
que hace que algunas veces se avergüencen.
Porque hay un ojo que ve en secreto (lo cual un día ustedes
conocerán) por cuya luz todo hombre será recompensado públicamente,
cuando Dios juzgue los secretos de toda la humanidad por Jesucristo, la luz del mundo.
Por lo tanto,
que nadie piense en su corazón que se podrá cubrir o esconder
con tan solo hablar de Sus palabras o profesar Su nombre,
o que será salvo por el perdón de pecados sin apartarse de la iniquidad.
Porque yo les digo de parte del Señor,
ay de todos los que toman cualquier cosa como su esperanza,
cubierta o refugio excepto la luz, vida y Espíritu puro del Dios vivo,
cuya gloria alumbra al mundo y cuyo resplandor pone en evidencia las cosas escondidas.
Así la esperanza del hipócrita perecerá, y los malos no se levantarán en el juicio,
y todas las cubiertas de injusticia serán demasiado estrechas ante la temible presencia
de Aquel que viene a juzgar al mundo con justicia y a los pueblos con verdad.
Pero Su luz resplandece en las conciencias y corazones de los hombres,
testificando contra toda injusticia que sea cometida por ellos,
reprobando y condenando la naturaleza injusta de la que se levanta,
y contendiendo con ellos a fin de llevarlos y guiarlos
a través del camino de santidad hacia Cristo,
el Salvador, de quien procede la luz, sin la cual ningún hombre verá al Señor.

Por lo tanto, todos los pueblos sobre la tierra vuelvan sus mentes a la luz,
con la cual han sido alumbrados por Cristo Jesús, el Salvador,
cuya luz les deja ver el pecado y la maldad.
Arrepiéntanse y valoren su tiempo, y no tapen sus oídos,
ni cierren sus ojos contra esa semilla en ustedes que se levanta para librarlos,
y que está contristada en medio de sus diversiones vanas,
y no puede satisfacerse con nada de este mundo.
Más bien presten atención a eso que les muestra la maldad del mundo,
porque esto los guiará fuera de él, y fuera de todos sus caminos, adoraciones,
modas y tradiciones, que son vanos y temporales, y los llevará a Cristo,
que no es del mundo, y que es la salvación de todos los que lo obedecen.
Y este es Aquel que me ha sacado del mundo a través de grandes tribulaciones,
y me ha llevado a la buena tierra de reposo.
Gloria a Aquel que se sienta en el trono, y al Cordero por los siglos de los siglos,
cuyo poder mató una vez, pero ahora da vida,
y habiendo matado la enemistad por la sangre de Su cruz,
Su propio brazo ha traído salvación.

Esto fue escrito en el verdadero amor a los del rebaño que todavía están esparcidos,
de quienes mi alma desea que lleguen a conocer el
descanso al mediodía en la vida del Hijo de Justicia, por

[.signed-section-signature]
William Bayly.

[.asterism]
'''

[.emphasized]
Después de haber sido convencido del evangelio eterno como se relata anteriormente,
y de haberse sentado por un tiempo bajo fuertes juicios
y profundas instrucciones en la escuela de Cristo,
William Bayly llegó a ser un eminente ministro en la antigua Sociedad de Amigos.
Los que mejor lo conocieron dijeron que era un hombre
que llevaba una vida inocente e irreprensible,
cuya conducta adornaba el evangelio en todos los sentidos,
y cuyas palabras daban gracia a los oyentes.
Como Apolos, "`él era un varón elocuente,
poderoso en las Escrituras,`" estando bien familiarizado tanto
con la historia como con el misterio de los oráculos de Dios,
a través de la asistencia de ese Espíritu que le dio un entendimiento verdadero de ambos.
John Crook una vez escribió de él, "`Si era lícito para Pablo, ese gran Apóstol,
relatar sin jactancia, sus propios sufrimientos y peligros en el mar y en la tierra,
por enemigos directos y amigos profesantes, etc. sin duda puedo relatar sin ofensa,
algo de los grandes sufrimientos de este buen hombre,
para que se pueda ver cómo no le fue dado solo creer y predicar la palabra de fe,
sino también sufrir por la misma.
Él una vez fue derribado,
tomado por el cabello y arrastrado en el suelo por crueles perseguidores,
y luego ellos intentaron separar y romper su boca y mandíbula de
tal manera que el suelo donde yacía quedó cubierto de sangre.
Y como si esta carnicería no hubiera sido suficiente para
convertirlo en un sacrificio idóneo para su crueldad,
un perseguidor corpulento y pesado golpeó su pecho con sus pies,
tratando de sacarle el aire de su cuerpo.
Y cuando este perseguidor hizo lo que quiso, le ordenó al carcelero que se lo llevara,
y lo pusiera en un asqueroso agujero para su alojamiento y curación.`" Pero William
Bayly sufrió tanto el abuso como el encarcelamiento con gran paciencia y constancia.
Y habiendo finalmente entregado su cuerpo en el servicio de Su Señor,
su esposa escribió de él lo siguiente:
"`Estoy completamente segura de que él dejó esta vida como un hombre limpio e inocente,
y como uno que deseaba el bien de toda la humanidad, y no buscaba lo suyo,
sino el honor de Dios.
Él no codiciaba el oro ni la plata de ningún hombre,
sino que gastó y fue gastado por el honor de Dios.
Su memoria vivirá, aunque su cuerpo ha sido removido.`"
